version: '3'
services:
  grass:
    build:
      context: .
      dockerfile: Dockerfile
      # image: jagerzhang/grass
    volumes:
      - ./data/accounts.txt:/grass/data/accounts.txt
      - ./data/proxies.txt:/grass/data/proxies.txt
    ports:
      - 8080:80
    environment:
      - MIN_PROXY_SCORE=50
      - CLAIM_REWARDS_ONLY=False                # claim tiers rewards only (https://app.getgrass.io/dashboard/referral-program)
      - REGISTER_ACCOUNT_ONLY=True
      - REGISTER_DELAY="(3, 7)"
      - THREADS=2                               # yalnızca hesap kaydı / ödül talep etme modunda
      - CHECK_POINTS=True                       # her hesap için yaklaşık 10 dakikada bir puanı göster
      - STOP_ACCOUNTS_WHEN_SITE_IS_DOWN=True    # proxy trafik kullanımını azaltmak için 20 dakika boyunca hesapları durdur
      - SHOW_LOGS_RARELY=False
      - ACCOUNTS_FILE_PATH="data/accounts.txt"
      - PROXIES_FILE_PATH="data/proxies.txt"
